from typing import Protocol
from uuid import UUID
from src.models.session_filters import SessionFilters

class ISessionRepository(Protocol):
    async def get_sessions(self, filters: SessionFilters) -> tuple[int, list]: ...
    async def get_session_by_id(self, session_id: UUID): ...
    async def search_sessions(self, search_query: str) -> list: ...

class ITrackRepository(Protocol):
    async def get_all_tracks(self) -> list: ...
